### ISSUE TITLE
求增加Climate Fan的set wind speed支持

### ISSUE THREAD

**Issue by RexS98** [feversky/aligenie#7]
Ha里根据Broadlink Climate添加了Fan。 并可以控制开关和风速，风速名称在Jason里把原来的low, medium , high改为了1挡，2挡-6挡。 如图。
天猫精灵目前可以控制打开风扇和关闭风扇，但是无法调整风速。 
说：天猫精灵，风速调为1挡
HA日志如下
2019-06-29 20:24:23 INFO (MainThread) [custom_components.aligenie] Handle Request: {'header': {'messageId': '8e5f8aad-0086-4d8b-9ba4-ab698afd28fd', 'name': 'SetWindSpeed', 'namespace': 'AliGenie.Iot.Device.Control', 'payLoadVersion': 1}, 'payload': {'accessToken': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI3NzFkMTFiMjdiYzM0NGZmOWIwOGQ1NTkwZjYwMjJjZSIsImlhdCI6MTU2MTgwNTY2NywiZXhwIjoxNTkzMzQxNjY3fQ.LODcpK-P3oAOjswzU1cH-vBmY2V2gsQM-LIdYeBue2w', 'attribute': 'windspeed', 'deviceId': 'fan.ke_ting_feng_shan', 'deviceType': 'fan', 'value': '1'}}
2019-06-29 20:24:23 ERROR (MainThread) [custom_components.aligenie] Traceback (most recent call last):
  File "/config/custom_components/aligenie.py", line 102, in post
    response = await handleRequest(data)
  File "/config/custom_components/aligenie.py", line 137, in handleRequest
    result = await controlDevice(name, payload)
  File "/config/custom_components/aligenie.py", line 247, in controlDevice
    result = await _hass.services.async_call(domain, service, data, True)
  File "/usr/src/app/homeassistant/core.py", line 1118, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: (ServiceNotFound(...), 'Service fan.set_wind_speed not found')

<img width="356" alt="屏幕快照 2019-06-29 下午9 33 16" src="https://user-images.githubusercontent.com/36916438/60384864-8d2ff800-9ab5-11e9-8f9b-7e4ff81aa723.png">

**Comment by feversky** [comment]
在脚本的TRANSLATIONS里面添加控制风扇的操作，如下：
TRANSLATIONS = {
    ....
    'fan': {
        'SetWindSpeed': lambda state, payload: ('set_speed', {'speed': payload['value']}),
    },
}
